{{- if .Values.avilaCloud.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "avila-cloud.fullname" . }}
  labels:
    {{- include "avila-cloud.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "avila-cloud.fullname" . }}
  minReplicas: {{ .Values.avilaCloud.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.avilaCloud.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.avilaCloud.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.avilaCloud.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.avilaCloud.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.avilaCloud.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
{{- end }}
